name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd centros-client
          npm ci
          npm run build
          rm -rf ../centros-server/src/dist
          mv dist ../centros-server/src
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v1
        with:
          dockerfile: centros-server/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.nush.app
          repository: centros
          tags: latest
